freebsd_build_task:
  env:
    ROSWELL_BRANCH: master
  freebsd_instance:
    matrix:
      image_family: freebsd-11-3-snap
    cpu: 1
    memory: 1G

  prepare_script:
    - pkg install -y gcc curl autoconf automake gmake bash git

  build_script:
    - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    - ros use sbcl-bin/system
    - git clone https://github.com/roswell/sbcl_bin.git
    - cd sbcl_bin;env METHOD=default ros -l Lakefile

