freebsd_build_task:
  env:
    ROSWELL_BRANCH: master
    OPTS: --with-sb-thread
  freebsd_instance:
    matrix:
      image_family: freebsd-11-3-snap
    cpu: 1
    memory: 1G

  prepare_script:
    - pkg install -y gcc curl autoconf automake gmake bash sbcl git

  build_script:
    - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    - ros use sbcl-bin/system
    - ros install snmsts/sn.github
    - git clone https://github.com/roswell/sbcl_bin.git
    - cd sbcl_bin;gmake latest-version archive

  binaries_artifacts:
    path: "sbcl_bin/*.bz2"
